version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Realmadridc.f631902
      - POSTGRES_DB=anuedb
    ports:
      - "5432:5432"